"""Add location field to Event

Revision ID: d148e738f146
Revises: 
Create Date: 2025-07-25 20:51:17.071988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd148e738f146'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_event')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.drop_column('venue')
        batch_op.drop_column('time')
        batch_op.drop_column('contact')
        batch_op.drop_column('status_class')
        batch_op.drop_column('status')
        batch_op.drop_column('organizer')
        batch_op.drop_column('address')
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('organizer', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('status_class', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('contact', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('venue', sa.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('location')

    op.create_table('_alembic_tmp_event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
